[project]
name = "arcgismcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arcgis>=2.4.1.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.3",
]
